In [2]:
#Import NumPy as np.
import numpy as np

In [ ]:
#Create a 1D array of numbers from 0 to 9.
array  = np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

In [ ]:
#Convert 1D array to 2D array with two rows.
array2 = np.reshape(array, (2, -1))
print(array2)

In [ ]:
#Write a NumPy program to create an array of the intergers from 30 to 70.
intergers_array = np.arange(30, 71)
print(intergers_array)

In [ ]:
#Write a NumPy program to append the values to the end of an array.

In [ ]:
# Create an existing array
append_array = np.array([10, 20, 30, 40])
print(append_array)

In [ ]:
# Create an array of integers from 30 to 70
new_values = np.arange(50, 61)
print(new_values)

In [ ]:
# Append new values to the existing array
resulting_array = np.append(append_array, new_values)
print(resulting_array)

In [ ]:
#Core Learning 1 - NumPy Fundamentals extension

In [ ]:
matrix= np.arange(1,10).reshape((3, 3))
#Print the matrix
print(matrix)
#blank space
print("")
#Give the size of the matrix
print(matrix.shape)

In [ ]:
#even integers from 30 to 70.
even_array = np.arange(30, 71, 2)
print(even_array)

In [ ]:
#List to an array
list = [1, 2, 3, 4]
print(list)
list_to_array = np.array(list)
print(list_to_array) #Prints list to array

In [ ]:
# Tuple to an array
tuple = (1, 2, 3, 4)
print(tuple) # prints the tuple

In [ ]:
#convert tuple to numpy array
tuple_to_array = np.array(tuple)
print(tuple_to_array) # prints the numpy array

In [ ]:
# Define the data type for the structured array using a list of tuples
data_type = [('name','S15'), ('class', int), ('height', float)]

# Define a list of student details
student_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

#Printing the data_type and student_details
print(data_type)
print(student_details)

In [ ]:
# Create a structured array using the student details and the defined data type
students = np.array(student_details, dtype=data_type)
print(students) #Prints the students information

In [ ]:
# Sort the structured array based on the 'height' field
sorted_students = np.sort(students, order='height')

# Print the sorted array
print(sorted_students) #Prints the sorted array

In [ ]:
#Core Learning 2 - Mathematics

In [ ]:
# Initialize two arrays
a = np.arange(30, 71)
b = np.arange(70, 111)

In [ ]:
#add arguments elementwise.
addition = np.add(a, b)
print(addition)

In [ ]:
#subtract arguments elementwise.
subtract = np.subtract(a, b)
print(subtract)

In [ ]:
#multiply arguments elementwise.
multiply = np.multiply(a, b)
print(multiply)

In [ ]:
#divide arguments elementwise.
divide = np.divide(a, b)
print(divide)

In [5]:
# preparing integers to round to the nearest integer
round = np.arange(1.5, 10.5)
print(round)

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [6]:
# round elements of an array to the nearest integer
round_new = np.round(round)
print(round_new)

[ 2.  2.  4.  4.  6.  6.  8.  8. 10.]


In [4]:
# Create two arrays
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([5, 4, 3, 2, 1])

In [ ]:
# Perform true division of the element-wise array inputs
result = np.true_divide(array_1, array_2)
print(result)

In [ ]:
#Core Learning 2 - Mathematics extension

In [ ]:
# Initialize first array
first = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(first)


In [ ]:
# Initialize first array
second = np.array([[11, 12], [13, 14], [15, 16]])
print(second)

In [ ]:
# Perform matrix multiplication between first and second
multiply = first.dot(second)
# Print the result
print(multiply)

In [ ]:
# Generate a random array of size 1000 with elements between 1 and 10
random_array = np.random.randint(1, 10, 1000)
print(random_array)

In [ ]:
# Calculate the average of elements in the random array
average_random_array = np.average(random_array)
print(average_random_array)

In [ ]:
# Calculate the variance of elements in the random array
variance_random_array = np.var(random_array)
print(variance_random_array)

In [ ]:
# Calculate the standard deviation of elements in the random array
std_random_array = np.std(random_array)
print(std_random_array)

In [ ]:
# Create an array of decimal numbers between 0 and 100 with 10 elements
random_intergers = np.random.rand(10) * 100

# Round the decimal numbers to 4 decimal places
random_array_2dp = np.round(random_intergers, 4)
print(random_array_2dp)

In [ ]:
# Round the decimal numbers to the nearest integer using the 'round' function
round_int = np.round(random_array_2dp)
print(round_int)

In [ ]:
# Round the decimal numbers down to the nearest integer using the 'floor' function
floor_int = np.floor(random_array_2dp)
print(floor_int)

In [ ]:
# Round the decimal numbers up to the nearest integer using the 'ceil' function
ceiling_int = np.ceil(random_array_2dp)
print(ceiling_int)

In [ ]:
# Truncate the decimal numbers using the 'trunc' function
trunc_int = np.trunc(random_array_2dp)
print(trunc_int)

In [ ]:
# Round the decimal numbers to 2 decimal places
round_dec_int = np.round(random_array_2dp, 2)
print(round_dec_int)

In [7]:
# Create a 1D array
arr = np.array([3, 4, 5, 2, 1, 6, 8, 9, 7])

In [8]:
# Find the maximum value
max_val = np.max(arr)
# Find the minimum value
min_val = np.min(arr)

In [9]:
print(f"minumum value: {min_val}, maxumum value: {max_val}")

minumum value: 1, maxumum value: 9


In [13]:
# Create two 1D arrays
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3,4,5,6,7])

In [14]:
# Concatenate the two arrays along axis 0
join = np.concatenate((arr1, arr2), axis=0)
print(join)

[1 2 3 4 5 6 7 1 2 3 4 5 6 7]
